"""
Professional PDF Report Generator for Sunnyside AI PV Simulator
Dependencies: fpdf2, Pillow, matplotlib, pandas, numpy
"""

import os
import io
import tempfile
from datetime import datetime
from typing import Dict, Any, Optional

try:
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    import matplotlib.patches as mpatches
    from matplotlib.backends.backend_agg import FigureCanvasAgg
except ImportError as _mpl_err:
    plt = None  # type: ignore
    import warnings
    warnings.warn(f"matplotlib not available for PDF charts: {_mpl_err}")

try:
    import numpy as np
except ImportError:
    np = None  # type: ignore

try:
    from fpdf import FPDF
except ImportError as _fpdf_err:
    raise ImportError(f"fpdf2 is required for PDF generation. Install: uv add fpdf2") from _fpdf_err

try:
    from PIL import Image
except ImportError as _pil_err:
    Image = None  # type: ignore
    import warnings
    warnings.warn(f"Pillow not available for PDF image processing: {_pil_err}")


class SunnysidePDF(FPDF):
    """Custom PDF class with professional solar report styling - Unicode support"""

    def __init__(self, company_name: str = "", author_name: str = "", logo_path: str = ""):
        super().__init__(orientation='P', unit='mm', format='A4')
        self.company_name = company_name
        self.author_name = author_name
        self.logo_path = logo_path
        self.set_auto_page_break(auto=True, margin=20)
        self.set_margins(15, 15, 15)
        # Unicode fonts
        self.ufont = "DejaVuSans"
        self.ufont_bold = "DejaVuSans-Bold"
        self.ufont_italic = "DejaVuSans-Oblique"
        # Register fonts with fallback logic
        import warnings
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            # Find DejaVu font files dynamically
            _FONT_DIRS = [
                '/usr/share/fonts/truetype/dejavu',
                '/usr/share/fonts/TTF',
                '/usr/share/fonts/truetype',
                '/usr/local/share/fonts',
            ]

            def find_font(name):
                for d in _FONT_DIRS:
                    path = os.path.join(d, name)
                    if os.path.exists(path):
                        return path
                return None

            def add_font_fallback(alias, preferred, fallback):
                """Try preferred font file, fall back to fallback if missing."""
                path = find_font(preferred)
                if not path:
                    path = find_font(fallback)
                if path:
                    self.add_font(alias, '', path, uni=True)
                # If no font found, FPdf defaults to Helvetica

            add_font_fallback(self.ufont, 'DejaVuSans.ttf', 'DejaVuSans.ttf')
            add_font_fallback(self.ufont_bold, 'DejaVuSans-Bold.ttf', 'DejaVuSans-Bold.ttf')
            add_font_fallback(self.ufont_italic, 'DejaVuSans-Oblique.ttf', 'DejaVuSansMono-Oblique.ttf')

    def header(self):
        # Gradient-like header bar
        self.set_fill_color(0, 20, 40)
        self.rect(0, 0, 210, 12, 'F')
        # Top accent line
        self.set_fill_color(0, 212, 255)
        self.rect(0, 12, 210, 1.5, 'F')
        # Logo
        if self.logo_path and os.path.exists(self.logo_path):
            try:
                self.image(self.logo_path, x=15, y=2, h=8)
            except Exception:
                pass
        # Company name
        self.set_xy(45 if (self.logo_path and os.path.exists(self.logo_path)) else 15, 3)
        self.set_font(self.ufont_bold, '', 10)
        self.set_text_color(255, 255, 255)
        if self.company_name:
            self.cell(0, 5, self.company_name, ln=0)
        # Right: app name
        self.set_xy(-80, 3)
        self.set_font(self.ufont, '', 9)
        self.set_text_color(0, 212, 255)
        self.cell(0, 5, 'Sunnyside AI | PV Simulator', ln=0, align='R')

    def footer(self):
        self.set_y(-20)
        self.set_fill_color(0, 212, 255)
        self.rect(0, self.get_y(), 210, 0.5, 'F')
        self.set_y(-15)
        self.set_font(self.ufont_italic, '', 8)
        self.set_text_color(120, 120, 120)
        left_text = f"Generated by Sunnyside AI on {datetime.now().strftime('%Y-%m-%d %H:%M')}"
        if self.author_name:
            left_text += f"  |  Prepared by: {self.author_name}"
        self.cell(0, 5, left_text, 0, 0, 'L')
        self.cell(0, 5, f'Page {self.page_no()}', 0, 0, 'R')

    def chapter_title(self, title: str, icon: str = ""):
        self.set_font(self.ufont_bold, '', 14)
        self.set_text_color(0, 212, 255)
        self.cell(0, 10, f"{icon}  {title}" if icon else title, ln=True)
        self.set_draw_color(0, 212, 255)
        self.line(15, self.get_y(), 195, self.get_y())
        self.ln(3)

    def chapter_body(self, text: str):
        self.set_font(self.ufont, '', 10)
        self.set_text_color(60, 60, 60)
        self.multi_cell(0, 6, text)
        self.ln(2)

    def info_row(self, label: str, value: str, unit: str = ""):
        self.set_font(self.ufont_bold, '', 10)
        self.set_text_color(80, 80, 80)
        self.cell(70, 6, f"{label}:", 0, 0)
        self.set_font(self.ufont, '', 10)
        self.set_text_color(0, 0, 0)
        display = f"{value} {unit}" if unit else str(value)
        self.cell(0, 6, display, 0, 1)

    def metric_box(self, label: str, value: str, unit: str = "", color: tuple = (0, 212, 255)):
        x = self.get_x()
        y = self.get_y()
        w = 55
        h = 28
        
        # Box background
        self.set_fill_color(245, 248, 250)
        self.rounded_rect(x, y, w, h, 3, 'F')
        
        # Accent bar
        self.set_fill_color(*color)
        self.rect(x, y, 3, h, 'F')
        
        # Label
        self.set_xy(x + 6, y + 4)
        self.set_font(self.ufont, '', 8)
        self.set_text_color(120, 120, 120)
        self.cell(w - 10, 5, label, 0, 2)
        
        # Value
        self.set_font(self.ufont_bold, '', 14)
        self.set_text_color(30, 30, 30)
        self.cell(w - 10, 8, f"{value} {unit}".strip(), 0, 0)
        
        self.set_xy(x + w + 5, y)

    def rounded_rect(self, x, y, w, h, r, style=''):
        """Draw a rounded rectangle"""
        self.set_draw_color(200, 200, 200)
        self.set_line_width(0.2)
        self.rect(x, y, w, h, style)


def create_monthly_chart(results: dict, width: int = 800, height: int = 350) -> str:
    """Create monthly production chart image"""
    months = list(results['monthly_kwh'].keys())
    values = list(results['monthly_kwh'].values())
    
    fig, ax = plt.subplots(figsize=(width / 100, height / 100), dpi=100)
    fig.patch.set_facecolor('#ffffff')
    ax.set_facecolor('#fafbfc')
    
    bars = ax.bar(months, values, color='#f59e0b', edgecolor='#d97706', linewidth=1.2, alpha=0.9)
    
    # Add value labels on top
    for bar in bars:
        height_bar = bar.get_height()
        ax.text(bar.get_x() + bar.get_width()/2., height_bar,
                f'{int(height_bar):,}',
                ha='center', va='bottom', fontsize=7, color='#4b5563')
    
    ax.set_xlabel('Month', fontsize=9, color='#374151')
    ax.set_ylabel('Energy (kWh)', fontsize=9, color='#374151')
    ax.set_title('Monthly Energy Production', fontsize=11, fontweight='bold', color='#111827', pad=10)
    ax.tick_params(colors='#6b7280', labelsize=8)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['left'].set_color('#e5e7eb')
    ax.spines['bottom'].set_color('#e5e7eb')
    ax.yaxis.grid(True, linestyle='--', alpha=0.4)
    
    plt.tight_layout()
    
    tmp_path = tempfile.mktemp(suffix='.png')
    fig.savefig(tmp_path, dpi=100, bbox_inches='tight', facecolor='white')
    plt.close(fig)
    return tmp_path


def create_hourly_sample_chart(results: dict, width: int = 800, height: int = 300) -> str:
    """Create hourly output sample chart"""
    hourly = results['hourly_output'].iloc[:168]  # First week
    
    fig, ax = plt.subplots(figsize=(width / 100, height / 100), dpi=100)
    fig.patch.set_facecolor('#ffffff')
    ax.set_facecolor('#fafbfc')
    
    ax.plot(range(len(hourly)), hourly.values, color='#3b82f6', linewidth=1.2, alpha=0.9)
    ax.fill_between(range(len(hourly)), hourly.values, alpha=0.15, color='#3b82f6')
    
    ax.set_xlabel('Hour', fontsize=9, color='#374151')
    ax.set_ylabel('AC Power (kW)', fontsize=9, color='#374151')
    ax.set_title('Hourly Output - First Week Sample', fontsize=11, fontweight='bold', color='#111827', pad=10)
    ax.tick_params(colors='#6b7280', labelsize=8)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['left'].set_color('#e5e7eb')
    ax.spines['bottom'].set_color('#e5e7eb')
    ax.yaxis.grid(True, linestyle='--', alpha=0.4)
    
    plt.tight_layout()
    
    tmp_path = tempfile.mktemp(suffix='.png')
    fig.savefig(tmp_path, dpi=100, bbox_inches='tight', facecolor='white')
    plt.close(fig)
    return tmp_path


def generate_pv_report_pdf(
    specs: dict,
    results: dict,
    solar: dict,
    company_name: str = "",
    author_name: str = "",
    logo_path: str = "",
    output_path: str = "pv_report.pdf"
) -> str:
    """Generate professional PDF report"""
    
    pdf = SunnysidePDF(company_name=company_name, author_name=author_name, logo_path=logo_path)
    
    # ========== PAGE 1: COVER + SUMMARY ==========
    pdf.add_page()
    
    # Title section
    pdf.set_y(40)
    pdf.set_font(pdf.ufont_bold, '', 26)
    pdf.set_text_color(0, 212, 255)
    pdf.cell(0, 12, 'PHOTOVOLTAIC SYSTEM', 0, 1, 'C')
    pdf.set_font(pdf.ufont_bold, '', 22)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 10, 'Performance Report', 0, 1, 'C')
    
    pdf.ln(5)
    pdf.set_font(pdf.ufont, '', 11)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, f"Location: {specs.get('name', 'Custom Location')}", 0, 1, 'C')
    pdf.cell(0, 6, f"Coordinates: {specs['latitude']:.4f}°, {specs['longitude']:.4f}°", 0, 1, 'C')
    pdf.cell(0, 6, f"Report Date: {datetime.now().strftime('%B %d, %Y')}", 0, 1, 'C')
    
    # Separator
    pdf.ln(8)
    pdf.set_draw_color(0, 212, 255)
    pdf.set_line_width(0.5)
    pdf.line(60, pdf.get_y(), 150, pdf.get_y())
    pdf.ln(8)
    
    # Key metrics row
    pdf.set_x(20)
    pdf.metric_box("Annual Production", f"{results['annual_kwh']:,.0f}", "kWh/yr", (245, 158, 11))
    pdf.metric_box("Specific Yield", f"{results['specific_yield']:.0f}", "kWh/kWp", (59, 130, 246))
    pdf.metric_box("Performance Ratio", f"{results['performance_ratio']:.1f}", "%", (16, 185, 129))
    
    pdf.ln(35)
    pdf.set_x(20)
    pdf.metric_box("System Cost", f"${results['system_cost']:,.0f}", "", (239, 68, 68))
    pdf.metric_box("Payback Period", f"{results['payback_years']:.1f}", "years", (139, 92, 246))
    pdf.metric_box("LCOE", f"${results['lcoe']:.3f}", "/kWh", (236, 72, 153))
    
    # ========== PAGE 2: LOCATION & SYSTEM ==========
    pdf.add_page()
    pdf.chapter_title("Location & System Configuration", "📍")
    
    pdf.set_font(pdf.ufont_bold, '', 11)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 8, 'Site Information', 0, 1)
    pdf.info_row('Project Name', specs.get('name', 'N/A'))
    pdf.info_row('Latitude', f"{specs['latitude']:.4f}", "deg")
    pdf.info_row('Longitude', f"{specs['longitude']:.4f}", "deg")
    pdf.info_row('Altitude', specs.get('altitude', 0), "m")
    pdf.info_row('Timezone', specs.get('timezone', 'UTC'))
    pdf.info_row('Climate Zone', 'Tropical' if abs(specs['latitude']) < 25 else 'Temperate')
    
    pdf.ln(4)
    pdf.set_font(pdf.ufont_bold, '', 11)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 8, 'Solar Geometry', 0, 1)
    pdf.info_row('Max Sun Elevation', f"{solar.get('max_elevation', 0):.1f}", "deg")
    pdf.info_row('Recommended Tilt', f"{specs.get('tilt', 0):.1f}", "deg")
    pdf.info_row('Array Azimuth', f"{specs.get('azimuth', 0):.0f}", "deg")
    dir_text = 'North-facing' if specs.get('azimuth', 0) == 0 else 'South-facing'
    pdf.info_row('Array Direction', dir_text)
    
    pdf.ln(4)
    pdf.set_font(pdf.ufont_bold, '', 11)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 8, 'System Design', 0, 1)
    pdf.info_row('DC Capacity', f"{results['dc_capacity_kw']:.1f}", "kW")
    pdf.info_row('AC Capacity', f"{results['ac_capacity_kw']:.1f}", "kW")
    pdf.info_row('Total Modules', str(results['num_modules']))
    pdf.info_row('Module Power', specs.get('module_power', 450), "W")
    pdf.info_row('Module Efficiency', specs.get('module_efficiency', 21.0), "%")
    pdf.info_row('Inverter Efficiency', specs.get('inverter_efficiency', 0.96) * 100, "%")
    
    # ========== PAGE 3: ENERGY PRODUCTION ==========
    pdf.add_page()
    pdf.chapter_title("Energy Production Analysis", "⚡")
    
    # Monthly chart
    monthly_chart_path = create_monthly_chart(results)
    pdf.image(monthly_chart_path, x=15, y=pdf.get_y(), w=180)
    pdf.ln(95)
    
    # Monthly table
    pdf.set_font(pdf.ufont_bold, '', 10)
    pdf.set_fill_color(0, 212, 255)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(35, 8, 'Month', 0, 0, 'C', fill=True)
    pdf.cell(50, 8, 'Energy (kWh)', 0, 0, 'C', fill=True)
    pdf.cell(50, 8, 'Daily Avg (kWh)', 0, 0, 'C', fill=True)
    pdf.cell(50, 8, '% of Annual', 0, 1, 'C', fill=True)
    
    pdf.set_font(pdf.ufont, '', 9)
    pdf.set_text_color(60, 60, 60)
    
    month_days = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    for i, (month, kwh) in enumerate(results['monthly_kwh'].items()):
        fill = i % 2 == 0
        if fill:
            pdf.set_fill_color(250, 250, 250)
        daily = kwh / month_days[i] if month_days[i] > 0 else 0
        pct = (kwh / results['annual_kwh'] * 100) if results['annual_kwh'] > 0 else 0
        
        pdf.cell(35, 7, month, 0, 0, 'C', fill=fill)
        pdf.cell(50, 7, f"{kwh:,.0f}", 0, 0, 'R', fill=fill)
        pdf.cell(50, 7, f"{daily:.1f}", 0, 0, 'R', fill=fill)
        pdf.cell(50, 7, f"{pct:.1f}%", 0, 1, 'R', fill=fill)
    
    # Total row
    pdf.set_font(pdf.ufont_bold, '', 9)
    pdf.set_fill_color(240, 248, 255)
    pdf.set_text_color(0, 100, 150)
    pdf.cell(35, 8, 'TOTAL', 0, 0, 'C', fill=True)
    pdf.cell(50, 8, f"{results['annual_kwh']:,.0f}", 0, 0, 'R', fill=True)
    pdf.cell(50, 8, f"{results['annual_kwh']/365:.1f}", 0, 0, 'R', fill=True)
    pdf.cell(50, 8, '100.0%', 0, 1, 'R', fill=True)
    
    # ========== PAGE 4: FINANCIAL ==========
    pdf.add_page()
    pdf.chapter_title("Financial Analysis", "💰")
    
    pdf.set_font(pdf.ufont_bold, '', 11)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 8, 'Investment Summary', 0, 1)
    
    pdf.info_row('System Cost', f"${results['system_cost']:,.2f}")
    pdf.info_row('Cost per Watt', f"${specs.get('cost_per_watt', 2.50):.2f}", "/W")
    pdf.info_row('Annual Savings', f"${results['annual_savings']:,.2f}", "/year")
    pdf.info_row('Simple Payback', f"{results['payback_years']:.1f}", "years")
    pdf.info_row('LCOE', f"${results['lcoe']:.4f}", "/kWh")
    
    pdf.ln(6)
    pdf.set_font(pdf.ufont_bold, '', 11)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 8, 'Performance Metrics', 0, 1)
    
    pdf.info_row('Capacity Factor', f"{results['capacity_factor']:.1f}", "%")
    pdf.info_row('Peak Output', f"{results['peak_power_kw']:.1f}", "kW")
    pdf.info_row('Specific Yield', f"{results['specific_yield']:.0f}", "kWh/kWp/year")
    
    # Disclaimer
    pdf.ln(10)
    pdf.set_font(pdf.ufont_italic, '', 8)
    pdf.set_text_color(150, 150, 150)
    pdf.multi_cell(0, 5, 
        "Disclaimer: This report is generated by Sunnyside AI photovoltiac simulation software using "
        "pvlib physics engine and synthetic weather data. Actual performance may vary based on "
        "local conditions, installation quality, and equipment degradation. This report is intended "
        "for preliminary feasibility assessment only. Consult a certified solar installer for "
        "detailed engineering and permitting."
    )
    
    # ========== PAGE 5: HOURLY SAMPLE ==========
    pdf.add_page()
    pdf.chapter_title("Hourly Output Sample", "📊")
    
    hourly_chart_path = create_hourly_sample_chart(results)
    pdf.image(hourly_chart_path, x=15, y=pdf.get_y(), w=180)
    pdf.ln(85)
    
    pdf.chapter_body(
        "The chart above shows the simulated AC power output for the first 168 hours (7 days) of the year. "
        "This sample illustrates the daily generation pattern including sunrise ramp-up, peak midday production, "
        "and evening curtailment. Cloud variability and seasonality effects are modeled using synthetic TMY data."
    )
    
    # Save
    pdf.output(output_path)
    
    # Cleanup temp files
    try:
        os.remove(monthly_chart_path)
        os.remove(hourly_chart_path)
    except Exception:
        pass
    
    return output_path


def generate_ai_analysis_pdf(
    ai_response: str,
    chat_history: list,
    specs: dict,
    results: dict,
    company_name: str = "",
    author_name: str = "",
    logo_path: str = "",
    output_path: str = "pv_ai_analysis.pdf"
) -> str:
    """Generate PDF of AI analysis and chat"""
    
    pdf = SunnysidePDF(company_name=company_name, author_name=author_name, logo_path=logo_path)
    
    # Cover
    pdf.add_page()
    pdf.set_y(50)
    pdf.set_font(pdf.ufont_bold, '', 24)
    pdf.set_text_color(0, 212, 255)
    pdf.cell(0, 12, 'AI-POWERED ANALYSIS', 0, 1, 'C')
    pdf.set_font(pdf.ufont_bold, '', 20)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 10, 'Sunnyside AI Advisory Report', 0, 1, 'C')
    pdf.ln(5)
    pdf.set_font(pdf.ufont, '', 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, f"Project: {specs.get('name', 'N/A')}", 0, 1, 'C')
    pdf.cell(0, 6, f"Generated: {datetime.now().strftime('%B %d, %Y at %H:%M')}", 0, 1, 'C')
    
    # AI Overview
    pdf.add_page()
    pdf.chapter_title("Executive AI Assessment", "🤖")
    
    pdf.set_font(pdf.ufont_bold, '', 11)
    pdf.set_text_color(0, 212, 255)
    pdf.cell(0, 8, 'System Overview', 0, 1)
    pdf.ln(1)
    
    pdf.info_row('Location', specs.get('name', 'N/A'))
    pdf.info_row('System Capacity', f"{results['dc_capacity_kw']:.1f}", "kW")
    pdf.info_row('Annual Production', f"{results['annual_kwh']:,.0f}", "kWh")
    pdf.info_row('Performance Ratio', f"{results['performance_ratio']:.1f}", "%")
    
    pdf.ln(5)
    pdf.set_font(pdf.ufont_bold, '', 11)
    pdf.set_text_color(0, 212, 255)
    pdf.cell(0, 8, 'AI Recommendations', 0, 1)
    pdf.ln(1)
    
    # AI response body
    pdf.set_font(pdf.ufont, '', 10)
    pdf.set_text_color(50, 50, 50)
    
    # Clean markdown-like formatting from AI response for PDF
    clean_response = ai_response.replace('**', '').replace('*', '').replace('#', '')
    pdf.multi_cell(0, 6, clean_response)
    
    pdf.ln(5)
    pdf.set_draw_color(0, 212, 255)
    pdf.set_line_width(0.3)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(3)
    pdf.set_font(pdf.ufont_italic, '', 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 5, "Analysis generated by Sunnyside AI using multi-agent LLM architecture.", 0, 1)
    
    # Chat history if available
    if chat_history and len(chat_history) > 1:
        pdf.add_page()
        pdf.chapter_title("Consultation Dialogue", "💬")
        
        for msg in chat_history:
            role = msg.get('role', '')
            content = msg.get('content', '')
            
            if role == 'user':
                pdf.set_font(pdf.ufont_bold, '', 10)
                pdf.set_text_color(59, 130, 246)
                pdf.cell(0, 7, 'User Question:', 0, 1)
                pdf.set_font(pdf.ufont, '', 9)
                pdf.set_text_color(60, 60, 60)
                pdf.multi_cell(0, 5, content.replace('**', ''))
                pdf.ln(2)
            elif role == 'assistant':
                pdf.set_font(pdf.ufont_bold, '', 10)
                pdf.set_text_color(245, 158, 11)
                pdf.cell(0, 7, 'Sunnyside AI:', 0, 1)
                pdf.set_font(pdf.ufont, '', 9)
                pdf.set_text_color(50, 50, 50)
                pdf.multi_cell(0, 5, content.replace('**', ''))
                pdf.ln(4)
                pdf.set_draw_color(230, 230, 230)
                pdf.line(15, pdf.get_y(), 195, pdf.get_y())
                pdf.ln(3)
    
    pdf.output(output_path)
    return output_path